version: '3'
services:
  app:
    build: .
    image: cabure
    volumes:
      - ".:/usr/src/app"
    environment:
      DB_HOST: db
      DB_USER: cabure
      DB_PASSWORD: PoStGrEsPaSsWoRd1337
      DB_NAME: cabure
      PYTHONPATH: '.'
    command: luigi --module cabure RunForYear --year 2018
    tty: true
    stdin_open: true
    depends_on:
      - db
      - scheduler
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: cabure
      POSTGRES_PASSWORD: PoStGrEsPaSsWoRd1337
      POSTGRES_DB: cabure
    ports:
      - "5432:5432"
    volumes:
      - caburedata:/var/lib/postgresql/data
  scheduler:
    image: cabure
    ports:
      - "8082:8082"
    command: luigid

volumes:
  caburedata: